apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    tier: monitoring
    app: alertmanager
data:
  alertmanager.yml: |-
    global:
      slack_api_url: https://hooks.slack.com/services/SADASDASDD/1234ASDADFFG/FCsdfdfdIWTjniH5sxbjE2JuU

    route:
      receiver: 'slack-notifications'

    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - channel: '#smalik-private-webhook-'
            icon_url: https://avatars3.githubusercontent.com/u/3380462
            send_resolved: true
            title: '[{{ .Status | toUpper }}] {{ .CommonAnnotations.title }}'
            text: |-
              {{ .CommonAnnotations.description }}
