apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    tier: monitoring
    app: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 10s

    rule_files:
      - rules.yml

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - localhost:9093

    scrape_configs:

    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']

    - job_name: 'external-applications'
      metrics_path: '/metrics/connected'
      honor_labels: true
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - default
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: prometheus-rsproxy
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: 8080

    - job_name: 'k8s-applications'
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - default
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_metrics_enabled]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_metrics_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_metrics_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: replace
          target_label: app
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: instance
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: env

  rules.yml: |-
    groups:
      - name: AllRules
        rules:
