apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    tier: monitoring
    app: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 60s
      scrape_timeout: 10s
      evaluation_interval: 10s

    rule_files:
      - rules.yml

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - localhost:9093

    scrape_configs:

    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']

    - job_name: 'proxied-applications'
      metrics_path: '/metrics/connected'
      honor_labels: true
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - default
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: prometheus-rsproxy
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: 8080

    - job_name: 'proxies'
      metrics_path: '/metrics/proxy'
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - default
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: prometheus-rsproxy
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: 8080
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: instance

  rules.yml: |-
    groups:
      - name: AllRules
        rules:
