apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    tier: monitoring
    app: grafana
spec:
  clusterIP: None
  selector:
    app: grafana
  ports:
    - name: web
      port: 80
      targetPort: web