apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    tier: monitoring
    app: grafana
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus:9090
      isDefault: true
  grafana.ini: |-
    [auth.anonymous]
    enabled = true

    # Organization name that should be used for unauthenticated users
    org_name = Main Org.

    # Role for unauthenticated users, other valid values are `Editor` and `Admin`
    org_role = Viewer
