{
 "title": "App Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(app_bar_total, env)"
   },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(app_bar_total{env=\"$env\"}, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "BAR per minute",
   "type": "graph",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (region)(rate(app_bar_total{env=\"$env\", app=\"$app\"}[2m])) * 60",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "FOO per minute",
   "type": "graph",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (region)(rate(app_foo_seconds_count{env=\"$env\", app=\"$app\"}[2m])) * 60",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}
{
 "title": "Spring Boot",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(jvm_memory_used_bytes, env)"
   },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(jvm_memory_used_bytes{env=\"$env\"}, app)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{env=\"$env\", app=\"$app\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{env=\"$env\", app=\"$app\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{env=\"$env\", app=\"$app\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{env=\"$env\", app=\"$app\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{env=\"$env\", app=\"$app\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{env=\"$env\", app=\"$app\", instance=\"$instance\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{env=\"$env\", app=\"$app\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "persistence_counts" },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{env=\"$env\", app=\"$app\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{env=\"$env\", app=\"$app\", instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{env=\"$env\", app=\"$app\", instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{env=\"$env\", app=\"$app\", instance=\"$instance\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{env=\"$env\", app=\"$app\", instance=\"$instance\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{env=\"$env\", app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{env=\"$env\", app=\"$app\",instance=\"$instance\"}[1m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{env=\"$env\", app=\"$app\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{env=\"$env\", app=\"$app\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{env=\"$env\", app=\"$app\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "count"
    }
   ]
  }
 ]
}