apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  labels:
    tier: monitoring
    app: grafana
spec:
  replicas: 1
  serviceName: grafana
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 5000
      containers:
        - name: grafana
          image: grafana/grafana:6.7.2
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: grafana-data-volume
              mountPath: /var/lib/grafana
              readOnly: false
            - name: grafana-config-volume
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
              readOnly: true
            - name: grafana-config-volume
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
              readOnly: true
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
            limits:
              cpu: 512m
              memory: 512Mi
      volumes:
        - name: grafana-config-volume
          configMap:
            name: grafana-config
            items:
              - key: datasource.yaml
                path: datasource.yaml
              - key: grafana.ini
                path: grafana.ini
  volumeClaimTemplates:
    - metadata:
        name: grafana-data-volume
        labels:
          tier: monitoring
          app: grafana
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi
