apiVersion: v1
kind: Service
metadata:
  name: prometheus-rsproxy
  labels:
    tier: monitoring
    app: prometheus-rsproxy
spec:
  type: LoadBalancer
  selector:
    app: prometheus-rsproxy
  ports:
    - name: scrape
      port: 8080
      targetPort: scrape
    - name: rsocket
      port: 7001
      targetPort: rsocket
